### ISSUE TITLE
visual

### ISSUE THREAD

**Issue by Avivali** [PathPlanning/Continuous-CBS#7]
I have a question ,How to realize the visualization of resultion like "Demos"  floder?

**Comment by aandreychuk** [comment]
You need to use the visualizing program :)
You can try to use mine. Note that it is based on Qt framework, so you need an appropriate IDE that is able to build it (Qt creator, for example).
For the correct work the log file needs to contain map (grid) and trajectories for all the agents. Note, that "standard" log-files provided by CCBS may contain additional <agent> tags that discribe agents' start and goal locations. They need to be removed, otherwise the visualizer will try to read these tags considering them as agents' trajectories.

[src.zip](https://github.com/PathPlanning/Continuous-CBS/files/9989172/src.zip)

**Comment by Avivali** [comment]
think you very much for detailed answers.
 I'm a Qt creator freshman,I didn't see a visual. And there are some problems as pictures.Could you give me your log.xml or some advises?
 Question1：Gtk-Message: 10:30:12.444: GtkDialog mapped without a transient parent. This is discouraged.
Somebody said that It is color error and does not affect operation, advised that use Qt's standard color dialog box instead of the operating system's native color dialog box.
Question2：The size of QPainter canvas is too large or too small.
I found that the code needs to read the length and width of the grid tag of the .xml file at mainwindow.cpp line 311. So I try to add <grid>, but nothing change.
![picture2](https://user-images.githubusercontent.com/104299225/201567267-bea65f84-b26f-4d26-9497-ef4da7a6e093.png)

**Comment by aandreychuk** [comment]
As I said, the input file should contain map. Accoring to your screenshot, you haven't added it into your file.
Here is an example, that should work.
[map_log_aa.zip](https://github.com/PathPlanning/Continuous-CBS/files/10006701/map_log_aa.zip)
